# Generated by Django 3.0.6 on 2020-06-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equip', '0017_auto_20200609_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd')], max_length=1, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Job')),
                ('press', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.Press')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='press',
            field=models.ManyToManyField(through='prod.JobInst', to='equip.Press'),
        ),
    ]
