# Generated by Django 3.0.6 on 2020-06-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
