# Generated by Django 3.0.6 on 2020-06-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_auto_20200610_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinst',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
