# Generated by Django 3.0.7 on 2020-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_auto_20200612_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinst',
            name='shift',
            field=models.IntegerField(blank=True, choices=[(1, '1st Shift'), (0, '2nd Shift'), (2, '3rd Shift'), (3, 'SAT')], null=True),
        ),
    ]
