# Generated by Django 3.0.7 on 2020-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_auto_20200612_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinst',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
