# Generated by Django 3.1.2 on 2020-10-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0008_auto_20200615_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinst',
            name='job',
        ),
        migrations.AlterField(
            model_name='jobinst',
            name='shift',
            field=models.IntegerField(blank=True, choices=[(1, '1st Shift'), (0, '2nd Shift')], null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
