# Generated by Django 3.1.2 on 2020-10-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_auto_20201029_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinst',
            name='comment',
        ),
    ]
