# Generated by Django 3.0.5 on 2020-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200331_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.TextField(),
        ),
    ]
