# Generated by Django 3.0.5 on 2020-04-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equip', '0003_auto_20200403_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnum', models.CharField(max_length=20)),
                ('descr', models.CharField(blank=True, max_length=35, null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press')),
            ],
        ),
    ]
