# Generated by Django 3.0.5 on 2020-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnum', models.CharField(max_length=35)),
                ('descr', models.TextField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.PositiveIntegerField()),
                ('marked_to_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addr1', models.CharField(blank=True, max_length=95, null=True)),
                ('addr2', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=35, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('vcomm', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
