# Generated by Django 3.0.5 on 2020-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_auto_20200403_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='quant',
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.CharField(default='items', max_length=5),
            preserve_default=False,
        ),
    ]
