# Generated by Django 3.0.5 on 2020-04-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_auto_20200404_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vcomm',
        ),
        migrations.AlterField(
            model_name='part',
            name='addr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='partnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='unit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='addr1',
            field=models.CharField(blank=True, max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='addr2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
