# Generated by Django 3.0.5 on 2020-05-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_auto_20200430_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['partnum']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
    ]
