# Generated by Django 3.0.6 on 2020-05-13 15:54

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_auto_20200501_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='textsearchable_index_col',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
