# Generated by Django 3.0.6 on 2020-05-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_part_textsearchable_index_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='textsearchable_index_col',
        ),
    ]
