# Generated by Django 3.0.5 on 2020-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0005_auto_20200404_1542'),
        ('invent', '0007_auto_20200404_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cat',
            field=models.ManyToManyField(to='equip.Press'),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendr',
            field=models.ManyToManyField(blank=True, to='invent.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='parts',
            field=models.ManyToManyField(blank=True, to='invent.Part'),
        ),
    ]
