# Generated by Django 3.0.7 on 2020-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0018_auto_20200616_0912'),
        ('invent', '0008_remove_part_textsearchable_index_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cat',
            field=models.ManyToManyField(blank=True, null=True, to='equip.Press'),
        ),
    ]
