# Generated by Django 3.0.5 on 2020-04-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_auto_20200404_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='addr',
        ),
    ]
