# Generated by Django 3.0.5 on 2020-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_remove_part_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partnum',
            field=models.CharField(default=1221312, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
