# Generated by Django 3.0.7 on 2020-06-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0027_pm'),
        ('invent', '0010_auto_20200616_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedpart',
            name='pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtn.Pm'),
        ),
    ]
