# Generated by Django 3.0.7 on 2020-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_usedpart_pm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='partnum',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
