# Generated by Django 3.0.5 on 2020-04-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_part_mwos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='mwos',
        ),
    ]
