# Generated by Django 3.0.7 on 2020-06-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_auto_20200617_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedpart',
            name='marked_to_delete',
        ),
    ]
