# Generated by Django 3.0.7 on 2020-06-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0029_auto_20200618_0622'),
        ('invent', '0013_remove_usedpart_marked_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedpart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mtn.Order'),
        ),
        migrations.AlterField(
            model_name='usedpart',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mtn.Pm'),
        ),
    ]
