# Generated by Django 3.1.2 on 2020-10-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0026_press_altname'),
        ('invent', '0014_auto_20200618_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedpart',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.pmsched'),
        ),
    ]
