# Generated by Django 3.0.5 on 2020-04-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_remove_vendor_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vendr',
            field=models.ManyToManyField(blank=True, default='All Vendors', to='invent.Vendor'),
        ),
    ]
