# Generated by Django 3.0.5 on 2020-04-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0008_order_parts'),
        ('invent', '0015_auto_20200408_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['partnum']},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='amount',
            new_name='amount_in_stock',
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invent.Part')),
                ('used_amount', models.PositiveIntegerField()),
                ('used_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtn.Order')),
            ],
            bases=('invent.part',),
        ),
    ]
