# Generated by Django 3.1.2 on 2020-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0015_auto_20201028_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
