# Generated by Django 3.0.5 on 2020-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0008_order_parts'),
        ('invent', '0016_auto_20200409_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='amount_in_stock',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='part',
            name='vendr',
            field=models.ManyToManyField(blank=True, to='invent.Vendor'),
        ),
        migrations.DeleteModel(
            name='UsedPart',
        ),
    ]
