# Generated by Django 3.0.5 on 2020-04-10 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0011_auto_20200410_0109'),
        ('invent', '0018_usedpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedpart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtn.Order'),
            preserve_default=False,
        ),
    ]
