# Generated by Django 3.0.5 on 2020-04-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0020_auto_20200410_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
