# Generated by Django 3.0.5 on 2020-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0021_auto_20200411_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vendr',
            field=models.ManyToManyField(to='invent.Vendor'),
        ),
        migrations.AlterField(
            model_name='usedpart',
            name='amount_used',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
