# Generated by Django 3.0.5 on 2020-04-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0022_auto_20200411_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedpart',
            name='marked_to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
