# Generated by Django 3.0.5 on 2020-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0023_usedpart_marked_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='addr2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
