# Generated by Django 3.0.5 on 2020-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0024_auto_20200412_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
