# Generated by Django 3.0.5 on 2020-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0025_auto_20200413_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='vendr',
            field=models.ManyToManyField(blank=True, to='invent.Vendor'),
        ),
    ]
