# Generated by Django 3.0.5 on 2020-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0026_auto_20200415_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partnum',
            field=models.CharField(max_length=35),
        ),
    ]
