# Generated by Django 3.0.5 on 2020-04-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equip', '0001_initial'),
        ('invent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(choices=[('RE', 'Repair'), ('ST', 'Setup'), ('PM', 'PM')], max_length=2)),
                ('descr', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('cause', models.CharField(blank=True, choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2, null=True)),
                ('descrrep', models.TextField(null=True)),
                ('timerep', models.DurationField(blank=True, null=True)),
                ('repdate', models.DateField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press')),
                ('origin', models.ForeignKey(limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.Employee')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parts', models.ManyToManyField(through='invent.UsedPart', to='invent.Part')),
                ('repby', models.ForeignKey(limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee')),
            ],
        ),
    ]
