# Generated by Django 3.0.4 on 2020-03-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('entry_filled', models.BooleanField(default=False)),
                ('repair_filled', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repby', models.CharField(max_length=20)),
                ('cause', models.CharField(choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('descrrep', models.TextField()),
                ('timerep', models.CharField(max_length=4)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtn.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=200)),
                ('descr', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtn.Order')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
