# Generated by Django 3.0.4 on 2020-04-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equip', '0002_auto_20200331_1813'),
        ('staff', '0002_auto_20200331_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('entry_filled', models.BooleanField(default=False)),
                ('repair_filled', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.IntegerField()),
                ('cause', models.CharField(choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2)),
                ('descrrep', models.TextField()),
                ('timerep', models.FloatField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtn.Order')),
                ('repby', models.ForeignKey(limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.IntegerField()),
                ('descr', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtn.Order')),
                ('origin', models.ForeignKey(limit_choices_to={'role': 'SV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
