# Generated by Django 3.0.4 on 2020-04-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ordertype',
            field=models.CharField(choices=[('RE', 'Repair'), ('ST', 'Setup'), ('PM', 'PM')], default='RE', max_length=2),
            preserve_default=False,
        ),
    ]
