# Generated by Django 3.0.5 on 2020-04-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('mtn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'SV'), ('role', 'MT'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.Employee'),
        ),
    ]
