# Generated by Django 3.0.4 on 2020-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cause',
            field=models.CharField(choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='descrrep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='repdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timerep',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
