# Generated by Django 3.0.4 on 2020-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
