# Generated by Django 3.0.4 on 2020-03-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('mtn', '0002_auto_20200331_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Employee'),
        ),
    ]
