# Generated by Django 3.0.4 on 2020-03-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0002_entry_entry_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_num',
        ),
    ]
