# Generated by Django 3.0.4 on 2020-04-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200331_1731'),
        ('mtn', '0003_auto_20200401_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cause',
            field=models.CharField(blank=True, choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='descrrep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='repby',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
    ]
