# Generated by Django 3.0.4 on 2020-03-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('mtn', '0003_auto_20200331_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
    ]
