# Generated by Django 3.0.5 on 2020-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='descr',
        ),
    ]
