# Generated by Django 3.0.4 on 2020-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0003_remove_entry_entry_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='won',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
