# Generated by Django 3.0.4 on 2020-03-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200331_1731'),
        ('mtn', '0004_auto_20200331_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='cause',
            field=models.CharField(choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repby',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
    ]
