# Generated by Django 3.0.4 on 2020-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0004_auto_20200401_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='repdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
