# Generated by Django 3.0.5 on 2020-05-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0004_remove_image_descr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
