# Generated by Django 3.0.4 on 2020-04-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0005_auto_20200401_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='entry_filled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='repair_filled',
        ),
    ]
