# Generated by Django 3.0.6 on 2020-05-13 15:26

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0005_auto_20200512_1352'),
    ]

    operations = [
        
    ]
