# Generated by Django 3.0.4 on 2020-03-31 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0002_auto_20200331_1813'),
        ('mtn', '0005_auto_20200331_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press'),
        ),
    ]
