# Generated by Django 3.0.4 on 2020-03-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0006_repair_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repby',
            field=models.CharField(choices=[('BR', 'Brad'), ('RO', 'Roman'), ('VA', 'Vadim')], max_length=2),
        ),
    ]
