# Generated by Django 3.0.4 on 2020-03-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0002_auto_20200331_1813'),
        ('staff', '0002_auto_20200331_1731'),
        ('mtn', '0006_auto_20200331_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.ForeignKey(limit_choices_to={'role': 'SV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repby',
            field=models.ForeignKey(limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='timerep',
            field=models.DurationField(),
        ),
    ]
