# Generated by Django 3.0.6 on 2020-05-13 15:54

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0006_order_textsearchable_index_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='textsearchable_index_col',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
