# Generated by Django 3.0.5 on 2020-04-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200331_1731'),
        ('mtn', '0006_auto_20200401_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cause',
            field=models.CharField(choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='descrrep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='repby',
            field=models.ForeignKey(limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='repdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timerep',
            field=models.FloatField(null=True),
        ),
    ]
