# Generated by Django 3.0.5 on 2020-04-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_auto_20200404_2010'),
        ('mtn', '0007_auto_20200403_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(blank=True, to='invent.Part'),
        ),
    ]
