# Generated by Django 3.0.4 on 2020-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0007_auto_20200331_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='timerep',
            field=models.IntegerField(blank=True),
        ),
    ]
