# Generated by Django 3.0.5 on 2020-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0018_usedpart'),
        ('mtn', '0008_order_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(blank=True, to='invent.UsedPart'),
        ),
    ]
