# Generated by Django 3.0.4 on 2020-03-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('mtn', '0009_auto_20200330_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Employee'),
        ),
    ]
