# Generated by Django 3.0.6 on 2020-05-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0009_auto_20200514_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='textsearchable_index_col',
        ),
    ]
