# Generated by Django 3.0.4 on 2020-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0010_auto_20200330_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.CharField(max_length=20),
        ),
    ]
