# Generated by Django 3.0.5 on 2020-04-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0018_usedpart'),
        ('mtn', '0010_auto_20200409_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(blank=True, to='invent.UsedPart'),
        ),
    ]
