# Generated by Django 3.0.6 on 2020-05-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0010_remove_order_textsearchable_index_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DN', 'Out of order'), ('IP', 'Repair in progress'), ('WP', 'Waiting for parts'), ('RD', 'Ready'), ('WR', 'Production')], default='RD', max_length=2),
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtn.Order')),
            ],
        ),
    ]
