# Generated by Django 3.0.5 on 2020-04-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0019_usedpart_order'),
        ('mtn', '0011_auto_20200410_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(through='invent.UsedPart', to='invent.Part'),
        ),
    ]
