# Generated by Django 3.0.6 on 2020-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0011_auto_20200528_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SB', 'Stand-by'), ('PR', 'Production'), ('DN', 'Out of order'), ('RE', 'Maintenance'), ('AP', 'Awaiting parts')], default='SB', max_length=2),
        ),
    ]
