# Generated by Django 3.0.5 on 2020-04-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0019_usedpart_order'),
        ('mtn', '0012_auto_20200410_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
	 migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(through='invent.UsedPart', to='invent.Part'),
        ),
    ]
