# Generated by Django 3.0.5 on 2020-04-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0012_auto_20200410_0148'),
        ('mtn', '0013_auto_20200410_0140'),
    ]

    operations = [
    ]
