# Generated by Django 3.0.6 on 2020-05-28 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtn', '0013_downtime_dt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='origin',
        ),
        migrations.AddField(
            model_name='downtime',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='dt_status',
            field=models.CharField(choices=[('PE', 'Idle'), ('RE', 'Work in progress'), ('AP', 'Awaiting parts')], default='SB', max_length=2),
        ),
    ]
