# Generated by Django 3.0.5 on 2020-04-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0015_order_cost_of_repair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost_of_repair',
            new_name='cost_of_parts',
        ),
    ]
