# Generated by Django 3.0.5 on 2020-04-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0016_auto_20200411_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost_of_parts',
        ),
    ]
