# Generated by Django 3.0.5 on 2020-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0017_remove_order_cost_of_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cause',
            field=models.CharField(blank=True, choices=[('NW', 'Normal Wear'), ('DM', 'Damage'), ('UN', 'Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timerep',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
