# Generated by Django 3.0.6 on 2020-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0017_auto_20200529_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='dt_type',
            field=models.CharField(choices=[('ID', 'Awaiting repair'), ('RE', 'Repair'), ('AP', 'Awaiting parts')], max_length=2),
        ),
    ]
