# Generated by Django 3.0.5 on 2020-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0018_auto_20200413_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='repdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
