# Generated by Django 3.0.6 on 2020-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0019_order_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timerepidle',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
