# Generated by Django 3.0.5 on 2020-04-23 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0020_auto_20200423_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
