# Generated by Django 3.0.6 on 2020-06-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0021_remove_order_repdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SB', 'Ready'), ('PR', 'Production'), ('DN', 'Out of order'), ('RE', 'Maintenance'), ('AP', 'Awaiting parts')], default='SB', max_length=2),
        ),
    ]
