# Generated by Django 3.0.5 on 2020-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0021_auto_20200423_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('RE', 'Repair')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='timerep',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
