# Generated by Django 3.0.5 on 2020-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0022_auto_20200424_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timerep',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
