# Generated by Django 3.0.6 on 2020-06-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0023_auto_20200601_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtime',
            name='dt_type',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='owner',
        ),
    ]
