# Generated by Django 3.0.6 on 2020-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0024_auto_20200602_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SB', 'Ready'), ('DN', 'Out of order'), ('RE', 'Maintenance'), ('AP', 'Awaiting parts')], default='SB', max_length=2),
        ),
    ]
