# Generated by Django 3.0.6 on 2020-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0025_auto_20200609_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='dttype',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
