# Generated by Django 3.0.7 on 2020-06-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0019_auto_20200616_1011'),
        ('invent', '0010_auto_20200616_1011'),
        ('staff', '0004_auto_20200616_1408'),
        ('mtn', '0026_downtime_dttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_required', models.DurationField(blank=True, null=True)),
                ('periodic', models.DurationField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('descr', models.TextField(blank=True, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press')),
                ('parts', models.ManyToManyField(through='invent.UsedPart', to='invent.Part')),
                ('repby', models.ForeignKey(blank=True, limit_choices_to={'role': 'MT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
