# Generated by Django 3.0.7 on 2020-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0027_pm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pm',
            options={'ordering': ['local']},
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='date',
            new_name='pm_date',
        ),
    ]
