# Generated by Django 3.0.7 on 2020-06-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0028_auto_20200617_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pm',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='mold',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('RE', 'Repair'), ('ST', 'Setup')], max_length=2),
        ),
    ]
