# Generated by Django 3.0.7 on 2020-06-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0020_auto_20200618_0641'),
        ('mtn', '0029_auto_20200618_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.Press'),
        ),
    ]
