# Generated by Django 3.0.7 on 2020-06-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0030_auto_20200618_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mold',
        ),
    ]
