# Generated by Django 3.0.7 on 2020-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0031_remove_order_mold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('RE', 'Repair'), ('ST', 'Setup'), ('MD', 'Mod')], max_length=2),
        ),
    ]
