# Generated by Django 3.0.7 on 2020-06-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0032_auto_20200623_1359'),
        ('mtn', '0032_auto_20200623_1407'),
    ]

    operations = [
    ]
