# Generated by Django 3.0.7 on 2020-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0034_auto_20200626_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('SB', 'Ready'), ('DN', 'Out of order'), ('RE', 'Maintenance'), ('AP', 'Awaiting parts')], default='SB', max_length=2),
        ),
    ]
