# Generated by Django 3.1.2 on 2020-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0036_image_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('RE', 'Repair'), ('ST', 'Setup'), ('MD', 'Mod'), ('PM', 'PM')], max_length=2),
        ),
    ]
