# Generated by Django 3.1.2 on 2020-10-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0037_auto_20201026_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed2',
            field=models.BooleanField(default=False),
        ),
    ]
