# Generated by Django 3.1.2 on 2020-10-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0038_order_closed2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed2',
        ),
    ]
