# Generated by Django 3.1.2 on 2020-10-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0015_auto_20201028_0733'),
        ('mtn', '0039_remove_order_closed2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pm',
        ),
    ]
