# Generated by Django 3.1.2 on 2020-11-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn', '0040_delete_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timerepidle',
        ),
    ]
