# Generated by Django 3.0.5 on 2020-04-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0002_auto_20200331_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='descr',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
