# Generated by Django 3.0.5 on 2020-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0002_auto_20200429_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='group',
            field=models.CharField(choices=[('PR', 'Presses'), ('GN', 'General'), ('BD', 'Building'), ('LF', 'LF')], default='GN', max_length=2),
            preserve_default=False,
        ),
    ]
