# Generated by Django 3.0.5 on 2020-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0003_auto_20200403_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='pname',
            field=models.TextField(),
        ),
    ]
