# Generated by Django 3.0.5 on 2020-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0003_press_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='press',
            options={'ordering': ['pname'], 'verbose_name_plural': 'presses'},
        ),
        migrations.AlterField(
            model_name='press',
            name='group',
            field=models.CharField(choices=[('PR', 'Production'), ('GN', 'General'), ('BD', 'Building'), ('LF', 'Lifting equipment')], max_length=2),
        ),
    ]
