# Generated by Django 3.0.5 on 2020-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0004_auto_20200430_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
