# Generated by Django 3.0.5 on 2020-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0005_press_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='contacts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
