# Generated by Django 3.0.5 on 2020-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0005_auto_20200404_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='status',
            field=models.CharField(choices=[('RE', 'Repair'), ('ST', 'Setup'), ('PM', 'PM'), ('OK', 'OK')], default='OK', max_length=2),
        ),
    ]
