# Generated by Django 3.0.5 on 2020-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0006_press_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='uploads',
            field=models.FileField(blank=True, null=True, upload_to='equip/'),
        ),
    ]
