# Generated by Django 3.0.5 on 2020-04-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0007_auto_20200422_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='status',
        ),
    ]
