# Generated by Django 3.0.5 on 2020-05-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0007_press_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.Press')),
            ],
        ),
    ]
