# Generated by Django 3.0.5 on 2020-05-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0008_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='press',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.Press'),
        ),
    ]
