# Generated by Django 3.0.5 on 2020-05-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0009_auto_20200508_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='uploads',
        ),
    ]
