# Generated by Django 3.0.6 on 2020-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0010_remove_press_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='subgroup',
            field=models.CharField(blank=True, choices=[('RG', 'Regular'), ('VC', 'Vacuum'), ('IN', 'Injection'), ('PN', 'Punching'), ('OT', 'Other')], max_length=2, null=True),
        ),
    ]
