# Generated by Django 3.0.6 on 2020-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0011_press_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='subgroup',
            field=models.CharField(blank=True, choices=[('CN', 'Conventional'), ('VC', 'Vacuum'), ('IN', 'Injection'), ('PN', 'Punching'), ('OT', 'Other')], max_length=2, null=True),
        ),
    ]
