# Generated by Django 3.0.6 on 2020-06-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0012_auto_20200514_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('press', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.Press')),
            ],
        ),
    ]
