# Generated by Django 3.0.6 on 2020-06-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0013_imprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=8, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('press', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.Press')),
            ],
        ),
    ]
