# Generated by Django 3.0.6 on 2020-06-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0014_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.CreateModel(
            name='JobInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd')], max_length=1, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.Job')),
            ],
        ),
    ]
