# Generated by Django 3.0.6 on 2020-06-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0015_auto_20200609_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinst',
            name='press',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.Press'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='press',
        ),
        migrations.AddField(
            model_name='job',
            name='press',
            field=models.ManyToManyField(through='equip.JobInst', to='equip.Press'),
        ),
    ]
