# Generated by Django 3.0.7 on 2020-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_remove_part_textsearchable_index_col'),
        ('equip', '0017_auto_20200609_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='part',
            field=models.ManyToManyField(blank=True, null=True, to='invent.Part'),
        ),
        migrations.RemoveField(
            model_name='upload',
            name='press',
        ),
        migrations.AddField(
            model_name='upload',
            name='press',
            field=models.ManyToManyField(blank=True, null=True, to='equip.Press'),
        ),
    ]
