# Generated by Django 3.0.7 on 2020-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0019_auto_20200616_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='group',
            field=models.CharField(choices=[('PR', 'Production'), ('GN', 'General'), ('BD', 'Building'), ('LF', 'Lifting equipment'), ('TL', 'Tooling')], max_length=2),
        ),
    ]
