# Generated by Django 3.1.2 on 2020-10-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_auto_20200618_0622'),
        ('equip', '0020_auto_20200618_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pmproc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.PositiveIntegerField(null=True)),
                ('pm_part_amount', models.PositiveIntegerField(null=True)),
                ('descr', models.TextField(null=True)),
                ('hours', models.PositiveIntegerField(null=True)),
                ('local', models.ManyToManyField(to='equip.Press')),
                ('pm_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.part')),
            ],
        ),
    ]
