# Generated by Django 3.1.2 on 2020-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0021_pmproc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmproc',
            name='local',
            field=models.ManyToManyField(blank=True, to='equip.Press'),
        ),
        migrations.CreateModel(
            name='Pmsched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('local', models.ManyToManyField(blank=True, null=True, to='equip.Press')),
            ],
        ),
    ]
