# Generated by Django 3.1.2 on 2020-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0023_auto_20201027_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsched',
            name='procs',
            field=models.ManyToManyField(blank=True, to='equip.Pmproc'),
        ),
    ]
