# Generated by Django 3.1.2 on 2020-10-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0016_auto_20201028_0835'),
        ('equip', '0026_press_altname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmproc',
            name='descr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='pmproc',
            name='local',
        ),
        migrations.AddField(
            model_name='pmproc',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.press'),
        ),
        migrations.AlterField(
            model_name='pmproc',
            name='pm_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.part'),
        ),
        migrations.AlterField(
            model_name='pmproc',
            name='pm_part_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
