# Generated by Django 3.1.2 on 2020-10-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0027_auto_20201028_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmsched',
            name='procs',
        ),
    ]
