# Generated by Django 3.1.2 on 2020-10-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0028_remove_pmsched_procs'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='joined',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.press'),
        ),
    ]
