# Generated by Django 3.1.2 on 2020-10-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0030_press_clocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='press',
            old_name='clocked',
            new_name='clocked1',
        ),
        migrations.AddField(
            model_name='press',
            name='clocked2',
            field=models.BooleanField(default=False),
        ),
    ]
