# Generated by Django 3.1.2 on 2020-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0031_auto_20201030_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
