# Generated by Django 3.1.2 on 2020-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0032_press_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='clocked1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='press',
            name='clocked2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='press',
            name='primary',
            field=models.BooleanField(),
        ),
    ]
