# Generated by Django 3.1.2 on 2020-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0033_auto_20201030_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='clocked1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='press',
            name='clocked2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='press',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
