# Generated by Django 3.1.2 on 2020-11-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip', '0035_auto_20201030_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmproc',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
